// Copyright 2026, Nick Kennedy
// SPDX-License-Identifier: BSL-1.0
#pragma once

static const char *macos_passthrough_shader_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct VSOut { float4 pos [[position]]; float2 uv; };\n"
    "vertex VSOut psvr2_pt_vs(uint vid [[vertex_id]]) {\n"
    "  float2 p[3] = {float2(-1,-1), float2(3,-1), float2(-1,3)};\n"
    "  VSOut o; o.pos=float4(p[vid],0,1);"
    "  o.uv=float2(p[vid].x*0.5+0.5, 1.0-(p[vid].y*0.5+0.5)); return o;\n"
    "}\n"
    "struct Camera { float4 intrinsics; float4 k; float4 rows[3]; };\n"
    "struct Params { float brightness; uint has_app; uint map_size; uint rotate; Camera cameras[2]; };\n"
    "float2 camera_uv(float2 tangent, constant Camera &c) {\n"
    "  float3 h=float3(tangent.x,-tangent.y,-1.0);\n"
    "  float3 ray=float3(dot(c.rows[0].xyz,h),-dot(c.rows[1].xyz,h),-dot(c.rows[2].xyz,h));\n"
    "  if (!all(isfinite(ray)) || ray.z<=0.0) return float2(-1.0);\n"
    "  float r=length(ray.xy); float theta=atan2(r,ray.z); float t2=theta*theta;\n"
    "  float d=theta*(1.0+t2*(c.k.x+t2*(c.k.y+t2*(c.k.z+t2*c.k.w))));\n"
    "  float2 pixel=c.intrinsics.xy*ray.xy*(r>1e-7 ? d/r : 0.0)+c.intrinsics.zw;\n"
    "  float2 uv=(pixel+0.5)/float2(1024.0,1016.0);\n"
    "  return all(isfinite(uv)) && d>=0.0 && all(uv>=0.0) && all(uv<=1.0) ? uv : float2(-1.0);\n"
    "}\n"
    "fragment float4 psvr2_pt_fs(VSOut in [[stage_in]],"
    " texture2d<float> app [[texture(0)]], texture2d<float> cam_l [[texture(1)]],"
    " texture2d<float> cam_r [[texture(2)]], texture2d<float, access::read> map_l [[texture(3)]],"
    " texture2d<float, access::read> map_r [[texture(4)]], constant Params &params [[buffer(0)]]) {\n"
    "  constexpr sampler s(coord::normalized, address::clamp_to_edge, filter::linear);\n"
    "  bool right = in.uv.x >= 0.5; float2 local_uv=float2(right ? (in.uv.x-0.5)*2.0 : in.uv.x*2.0, in.uv.y);\n"
    "  uint2 mi=uint2(min(uint(local_uv.x*float(params.map_size)), params.map_size-1),"
    "                 min(uint(local_uv.y*float(params.map_size)), params.map_size-1));\n"
    "  float4 mapping = right ? map_r.read(mi) : map_l.read(mi);\n"
    "  float2 cuv = params.rotate != 0 ? camera_uv(mapping.zw,params.cameras[right ? 1 : 0]) : mapping.xy;\n"
    "  float3 camera=float3(0.0);"
    "  if (cuv.x >= 0.0 && cuv.y >= 0.0) { float g=(right ? cam_r.sample(s,cuv).r : cam_l.sample(s,cuv).r);"
    "    camera=float3(saturate(g*params.brightness)); }\n"
    "  if (params.has_app != 0) { float4 a=app.sample(s,in.uv); return float4(a.rgb + camera*(1.0-a.a), 1.0); "
    "}\n"
    "  return float4(camera,1.0);\n"
    "}\n";
